# Generated by Django 4.2.7 on 2024-05-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "startups",
            "0013_alter_readinesslevelcriterionanswer_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinesslevelcriterionanswer",
            name="startup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readiness_level_criterion_answers",
                to="startups.startup",
            ),
        ),
    ]
