# Generated by Django 4.2.7 on 2024-05-14 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("startups", "0014_alter_readinesslevelcriterionanswer_startup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startup",
            name="member_1_email",
        ),
        migrations.RemoveField(
            model_name="startup",
            name="member_1_name",
        ),
        migrations.RemoveField(
            model_name="startup",
            name="member_1_number",
        ),
        migrations.RemoveField(
            model_name="startupmember",
            name="email",
        ),
        migrations.AlterField(
            model_name="startupmember",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
