# Generated by Django 4.2.7 on 2024-05-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0015_remove_startup_member_1_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapsuleProposalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("title", models.CharField(max_length=50)),
                ("startup_description", models.CharField(max_length=100)),
                ("problem_statement", models.CharField(max_length=200)),
                ("target_market", models.CharField(max_length=100)),
                ("solution_description", models.CharField(max_length=500)),
                ("objectives", models.CharField(max_length=50)),
                ("scope", models.CharField(max_length=50)),
                ("methodology", models.CharField(max_length=300)),
                (
                    "startup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capsule_proposal_info",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "db_table": "capsule_proposals_info",
            },
        ),
    ]
