# Generated by Django 4.2.7 on 2024-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0017_startuprna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="methodology",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="objectives",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="problem_statement",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="scope",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="solution_description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="startup_description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="target_market",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="capsuleproposalinfo",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
