# Generated by Django 4.2.7 on 2024-10-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0018_alter_capsuleproposalinfo_methodology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startuprna",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
