# Generated by Django 4.2.7 on 2024-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0020_cohort_startupcontractedmember_elevatelog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startupreadinesslevel",
            name="remark",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
