# Generated by Django 4.2.7 on 2024-12-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0021_startupreadinesslevel_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="cohort",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startups",
                to="startups.cohort",
            ),
        ),
    ]
