# Generated by Django 4.2.7 on 2024-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="initiative_number",
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="roadblock",
            name="risk_number",
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority_number",
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
