# Generated by Django 4.2.7 on 2024-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_initiative_initiative_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="measures",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="remarks",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="targets",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="roadblock",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="roadblock",
            name="fix",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
