# Generated by Django 4.2.7 on 2024-10-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_initiative_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roadblock",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
