# Generated by Django 4.2.7 on 2024-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_initiative_assignee_task_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadblock",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "For Review"),
                    (2, "Discontinued"),
                    (3, "Delayed"),
                    (4, "Scheduled"),
                    (5, "On Track"),
                    (6, "Completed"),
                ],
                default=1,
            ),
        ),
    ]
