# Generated by Django 4.2.7 on 2024-12-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_roadblock_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="initiative",
            options={"ordering": ["order", "initiative_number"]},
        ),
        migrations.AlterModelOptions(
            name="roadblock",
            options={"ordering": ["order", "risk_number"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order", "priority_number"]},
        ),
        migrations.AddField(
            model_name="initiative",
            name="order",
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="roadblock",
            name="order",
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
